---
config:
  interval: 2
  iNEWS_Server:
    Username: 'avid'
    Password: 'inews'
    Servername: '192.168.70.166'
    Current_Queue: '[INEWS4X]SHOW.TRAINING.RUNDOWN'
  iNEWS_WSAPI:
    wsdl: 'http://192.168.70.177:8080'
  iNEWS_Client:
    field_id: 'app'
    NumberOfStoriesToGet: 225
